# Kubernetes Service for exposing HTTP + QUIC

apiVersion: v1
kind: Service
metadata:
  name: bouncing-ball-service
spec:
  type: NodePort
  selector:
    app: bouncing-ball
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 8080
      targetPort: 8080
      protocol: UDP
      name: quic
